services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    # Uncomment to use custom config
    # volumes:
    #   - ./grafana_config/:/etc/grafana/
    # environment:
    #   - GF_PATHS_CONFIG=/etc/grafana/custom.ini
