services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    # Uncomment to use custom config
    # volumes:
    #   - ./grafana_config/:/etc/grafana/
    # environment:
    #   - GF_PATHS_CONFIG=/etc/grafana/custom.ini

  db:
    image: postgres
    container_name: membrane_pef_test_local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: membrane_pef_test_pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@m87.ai
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
