{
 "title": "Process Info",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Element Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "countSeries(removeEmptySeries(stats.gauges.recon.process.memory_used.binary_memory.*.BufferPushSource.*))"
    },
    {
     "target": "countSeries(removeEmptySeries(stats.gauges.recon.process.memory_used.binary_memory.*.BufferFilter.*))"
    },
    {
     "target": "countSeries(removeEmptySeries(stats.gauges.recon.process.memory_used.binary_memory.*.BufferSink.*))"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.recon.process.memory_used.memory.value.*.*"
    }
   ]
  },
  {
   "title": "Binary Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.recon.process.memory_used.binary_memory.value.*.*"
    }
   ]
  },
  {
   "title": "Filter Binary Memory P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "percentileOfSeries(stats.gauges.recon.process.memory_used.binary_memory.value.BufferFilter.*, 99, false)"
    }
   ]
  },
  {
   "title": "Sink Binary Memory P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "percentileOfSeries(stats.gauges.recon.process.memory_used.binary_memory.value.BufferSink.*, 99, false)"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.recon.process.memory_used.heap_size.value.*.*"
    }
   ]
  },
  {
   "title": "Total Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.recon.process.memory_used.total_heap_size.value.*.*"
    }
   ]
  },
  {
   "title": "Message Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "stats.gauges.recon.process.memory_used.message_queue_len.value.*.*"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "target": "stats.gauges.recon.process.memory_used.garbage_collection.*.value.*.*"
    }
   ]
  },
  {
   "title": "Reductions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "target": "stats.gauges.recon.process.work.reductions.value.*.*"
    }
   ]
  }
 ]
}