{
 "title": "VM Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Recon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.recon_alloc.memory.allocated.value"
    },
    {
     "target": "stats.gauges.recon_alloc.memory.used.value"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "stats.gauges.recon_alloc.memory.allocated.value"
    },
    {
     "target": "stats.gauges.recon_alloc.memory.used.value"
    }
   ]
  },
  { "title": "VMStats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "VM Binary Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.vmstats.memory.binary.value"
    }
   ]
  },
  {
   "title": "VM Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.vmstats.memory.total.value"
    }
   ]
  },
  {
   "title": "VM Memory (other)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.vmstats.memory.atom_used.value"
    },
    {
     "target": "stats.gauges.vmstats.memory.ets.value"
    },
    {
     "target": "stats.gauges.vmstats.memory.procs_used.value"
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.vmstats.gc.words_reclaimed.value"
    },
    {
     "target": "stats.gauges.vmstats.gc.count.value"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "stats.gauges.vmstats.io.*.value"
    }
   ]
  }
 ]
}