scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'membrane_performance_test'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:4000']
